import Head from "next/head";
import Image from "next/image";
import Featured from "@/components/Featured";
import BowlList from "@/components/BowlList";
import axios from "axios";
import AddButton from "@/components/AddButton";
import Add from "@/components/Add";
import { useState } from "react";

axios.defaults.baseURL = process.env.APP_URL;

export default function Home({ bowlList, isAdmin }) {
  const [close, setClose] = useState(true);
  return (
    <div >
      <Head>
        <title>Pikko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Featured />
      {isAdmin && <AddButton setClose={setClose} />}
      <BowlList bowlList={bowlList} />
      {!close && <Add setClose={setClose} />}
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let isAdmin = false;

  if (myCookie.token === process.env.TOKEN) {
    isAdmin = true;
  }

  const res = await axios.get("/api/products");
  return {
    props: {
      bowlList: res.data,
      isAdmin
    }
  };
};
