import Head from "next/head";
import Image from "next/image";
import Featured from "@/components/Featured";
import BowlList from "@/components/BowlList";
import axios from "axios";

export default function Home({ bowlList }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <BowlList bowlList={bowlList} />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      bowlList: res.data
    }
  };
};
